spring:
  application:
    name: notification_service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true